export const verfiyOtpConstant = {
    VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE"
};
export const getUserDetailsConstant = {
    GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE"
};
export const updateUserDetailsConstant = {
    UPDATE_USER_DETAILS_REQUEST: "UPDATE_USER_DETAILS_REQUEST",
    UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
    UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE"
};
export const getUserListConstants = {
    GET_USER_LIST_REQUEST: "GET_USER_LIST_REQUEST",
    GET_USER_LIST_SUCCESS: "GET_USER_LIST_SUCCESS",
    GET_USER_LIST_FAILURE: "GET_USER_LIST_FAILURE"
};
export const getMessagesConstants = {
    GET_MESSAGE_REQUEST: "GET_MESSAGE_REQUEST",
    GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
    GET_MESSAGE_FAILURE: "GET_MESSAGE_FAILURE"
};
export const sendMessagesConstants = {
    SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE"
};
