export const verfiyOtpConstant = {
    VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAILURE: "VERIFY_OTP_FAILURE"
};
export const getUserDetailsConstant = {
    GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
    GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
    GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE"
};
export const updateUserDetailsConstant = {
    UPDATE_USER_DETAILS_REQUEST: "UPDATE_USER_DETAILS_REQUEST",
    UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
    UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE"
};
