export const commonConstants = {
  UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_REQUEST_SUCCESS: "UPLOAD_IMAGE_REQUEST_SUCCESS",
  UPLOAD_IMAGE_REQUEST_FAILURE: "UPLOAD_IMAGE_REQUEST_FAILURE",
  UPLOAD_IMAGE_FILE_REQUEST: "UPLOAD_IMAGE_FILE_REQUEST",
  UPLOAD_IMAGE_FILE_REQUEST_SUCCESS: "UPLOAD_IMAGE_FILE_REQUEST_SUCCESS",
  UPLOAD_IMAGE_FILE_REQUEST_FAILURE: "UPLOAD_IMAGE_FILE_REQUEST_FAILURE",
};

export const resumeParserConstants = {
  RESUME_PARSER_REQUEST: "RESUME_PARSER_REQUEST",
  RESUME_PARSER_SUCCESS: "RESUME_PARSER_SUCCESS",
  RESUME_PARSER_FAILURE: "RESUME_PARSER_FAILURE",
};

export const createJobConstants = {
  CREATE_JOB_REQUEST: "CREATE_JOB_REQUEST",
  CREATE_JOB_REQUEST_SUCCESS: "CREATE_JOB_REQUEST_SUCCESS",
  CREATE_JOB_REQUEST_FAILURE: "CREATE_JOB_REQUEST_FAILURE",
};
export const updateJobConstants = {
  UPDATE_JOB_REQUEST: "UPDATE_JOB_REQUEST",
  UPDATE_JOB_SUCCESS: "UPDATE_JOB_SUCCESS",
  UPDATE_JOB_FAILURE: "UPDATE_JOB_FAILURE",
};
export const updateJobApplicationConstants = {
  UPDATE_APPLICATION_REQUEST: "UPDATE_APPLICATION_REQUEST",
  UPDATE_APPLICATION_SUCCESS: "UPDATE_APPLICATION_SUCCESS",
  UPDATE_APPLICATION_FAILURE: "UPDATE_APPLICATION_FAILURE",
};
export const addCandidateConstants = {
  ADD_CANDIDATE_REQUEST: "ADD_CANDIDATE_REQUEST",
  ADD_CANDIDATE_SUCCESS: "ADD_CANDIDATE_SUCCESS",
  ADD_CANDIDATE_FAILURE: "ADD_CANDIDATE_FAILURE",
};

export const getJobConstants = {
  GET_JOB_REQUEST: "GET_JOB_REQUEST",
  GET_JOB_REQUEST_SUCCESS: "GET_JOB_REQUEST_SUCCESS",
  GET_JOB_REQUEST_FAILURE: "GET_JOB_REQUEST_FAILURE",
};
export const getJobDetailConstants = {
  GET_JOB_DETAIL_REQUEST: "GET_JOB_DETAIL_REQUEST",
  GET_JOB_DETAIL_SUCCESS: "GET_JOB_DETAIL_SUCCESS",
  GET_JOB_DETAIL_FAILURE: "GET_JOB_DETAIL_FAILURE",
};
export const logoutConstants = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};
export const applyJobConstants = {
  APPLY_JOB_REQUEST: "APPLY_JOB_REQUEST",
  APPLY_JOB_SUCCESS: "APPLY_JOB_SUCCESS",
  APPLY_JOB_FAILURE: "APPLY_JOB_FAILURE",
};
export const getAllCandidateActions = {
  GET_ALL_CANDIDATE_REQUEST: "GET_ALL_CANDIDATE_REQUEST",
  GET_ALL_CANDIDATE_SUCCESS: "GET_ALL_CANDIDATE_SUCCESS",
  GET_ALL_CANDIDATE_FAILURE: "GET_ALL_CANDIDATE_FAILURE",
};
export const addClientConstants = {
  ADD_CLIENT_REQUEST: "ADD_CLIENT_REQUEST",
  ADD_CLIENT_SUCCESS: "ADD_CLIENT_SUCCESS",
  ADD_CLIENT_FAILURE: "ADD_CLIENT_FAILURE",
};
export const getClientJobsConstants = {
  GET_CLIENT_JOBS_REQUEST: "GET_CLIENT_JOBS_REQUEST",
  GET_CLIENT_JOBS_SUCCESS: "GET_CLIENT_JOBS_SUCCESS",
  GET_CLIENT_JOBS_FAILURE: "GET_CLIENT_JOBS_FAILURE",
};
export const getClientListConstants = {
  GET_CLIENT_LIST_REQUEST: "GET_CLIENT_LIST_REQUEST",
  GET_CLIENT_LIST_SUCCESS: "GET_CLIENT_LIST_SUCCESS",
  GET_CLIENT_LIST_FAILURE: "GET_CLIENT_LIST_FAILURE",
};
export const getClientDetailsConstants = {
  GET_CLIENT_DETAIL_REQUEST: "GET_CLIENT_DETAIL_REQUEST",
  GET_CLIENT_DETAIL_SUCCESS: "GET_CLIENT_DETAIL_SUCCESS",
  GET_CLIENT_DETAIL_FAILURE: "GET_CLIENT_DETAIL_FAILURE",
};
export const updateClientDetailsConstants = {
  UPDATE_CLIENT_DETAIL_REQUEST: "UPDATE_CLIENT_DETAIL_REQUEST",
  UPDATE_CLIENT_DETAIL_SUCCESS: "UPDATE_CLIENT_DETAIL_SUCCESS",
  UPDATE_CLIENT_DETAIL_FAILURE: "UPDATE_CLIENT_DETAIL_FAILURE",
};

export const getCandidateProfileConstants = {
  CANDIDATE_PROFILE_REQUEST: "CANDIDATE_PROFILE_REQUEST",
  CANDIDATE_PROFILE_SUCCESS: "CANDIDATE_PROFILE_SUCCESS",
  CANDIDATE_PROFILE_FAILURE: "CANDIDATE_PROFILE_FAILURE",
};
export const signupUserConstants = {
  SIGNUP_USER_REQUEST: "SIGNUP_USER_REQUEST",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
};
export const getuserDetailsConstants = {
  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
};
export const updateUserDetailsConstants = {
  UPDATE_USER_DETAILS_REQUEST: "UPDATE_USER_DETAILS_REQUEST",
  UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
  UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE",
};
export const loginUserConstants = {
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
};
export const createPermissionConstants = {
  ADD_PERMISSIONS_REQUEST: "ADD_PERMISSIONS_REQUEST",
  ADD_PERMISSIONS_SUCCESS: "ADD_PERMISSIONS_SUCCESS",
  ADD_PERMISSIONS_FAILURE: "ADD_PERMISSIONS_FAILURE",
};
export const getPermissionConstants = {
  GET_PERMISSIONS_REQUEST: "GET_PERMISSIONS_REQUEST",
  GET_PERMISSIONS_SUCCESS: "GET_PERMISSIONS_SUCCESS",
  GET_PERMISSIONS_FAILURE: "GET_PERMISSIONS_FAILURE",
};
export const updatePermissionConstants = {
  UPDATE_PERMISSIONS_REQUEST: "UPDATE_PERMISSIONS_REQUEST",
  UPDATE_PERMISSIONS_SUCCESS: "UPDATE_PERMISSIONS_SUCCESS",
  UPDATE_PERMISSIONS_FAILURE: "UPDATE_PERMISSIONS_FAILURE",
};
export const createUserConstants = {
  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",
};
export const getUserConstants = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
};
export const createRoleConstants = {
  ADD_ROLE_REQUEST: "ADD_ROLE_REQUEST",
  ADD_ROLE_SUCCESS: "ADD_ROLE_SUCCESS",
  ADD_ROLE_FAILURE: "ADD_ROLE_FAILURE",
};
export const getRoleConstants = {
  GET_ROLE_REQUEST: "GET_ROLE_REQUEST",
  GET_ROLE_SUCCESS: "GET_ROLE_SUCCESS",
  GET_ROLE_FAILURE: "GET_ROLE_FAILURE",
};
export const getJobApplicationConstants = {
  GET_JOB_APPLICATION_REQUEST: "GET_JOB_APPLICATION_REQUEST",
  GET_JOB_APPLICATION_SUCCESS: "GET_JOB_APPLICATION_SUCCESS",
  GET_JOB_APPLICATION_FAILURE: "GET_JOB_APPLICATION_FAILURE",
};
export const updateRoleConstants = {
  UPDATE_ROLE_REQUEST: "UPDATE_ROLE_REQUEST",
  UPDATE_ROLE_SUCCESS: "UPDATE_ROLE_SUCCESS",
  UPDATE_ROLE_FAILURE: "UPDATE_ROLE_FAILURE",
};
export const postFeedbackConstants = {
  POST_FEEDBACK_REQUEST: "POST_FEEDBACK_REQUEST",
  POST_FEEDBACK_SUCCESS: "POST_FEEDBACK_SUCCESS",
  POST_FEEDBACK_FAILURE: "POST_FEEDBACK_FAILURE",
};

export const getUserPermissionConstants = {
  GET_USER_PERMISSIONS_REQUEST: "GET_USER_PERMISSIONS_REQUEST",
  GET_USER_PERMISSIONS_SUCCESS: "GET_USER_PERMISSIONS_SUCCESS",
  GET_USER_PERMISSIONS_FAILURE: "GET_USER_PERMISSIONS_FAILURE",
};

export const getInterviewerListConstants = {
  GET_INTERVIEWER_LIST_REQUEST: "GET_INTERVIEWER_LIST_REQUEST",
  GET_INTERVIEWER_LIST_SUCCESS: "GET_INTERVIEWER_LIST_SUCCESS",
  GET_INTERVIEWER_LIST_FAILURE: "GET_INTERVIEWER_LIST_FAILURE",
};
export const getInterviewerReportConstants = {
  GET_INTERVIEWER_REPORT_REQUEST: "GET_INTERVIEWER_REPORT_REQUEST",
  GET_INTERVIEWER_REPORT_SUCCESS: "GET_INTERVIEWER_REPORT_SUCCESS",
  GET_INTERVIEWER_REPORT_FAILURE: "GET_INTERVIEWER_REPORT_FAILURE",
};
export const getInterviewDetailsConstants = {
  GET_INTERVIEW_DETAILS_REQUEST: "GET_INTERVIEW_DETAILS_REQUEST",
  GET_INTERVIEW_DETAILS_SUCCESS: "GET_INTERVIEW_DETAILS_SUCCESS",
  GET_INTERVIEW_DETAILS_FAILURE: "GET_INTERVIEW_DETAILS_FAILURE",
};
export const getAllScheduleInterviewListConstants = {
  GET_SCHEDULE_INTERVIEW_LIST_REQUEST: "GET_SCHEDULE_INTERVIEW_LIST_REQUEST",
  GET_SCHEDULE_INTERVIEW_LIST_SUCCESS: "GET_SCHEDULE_INTERVIEW_LIST_SUCCESS",
  GET_SCHEDULE_INTERVIEW_LIST_FAILURE: "GET_SCHEDULE_INTERVIEW_LIST_FAILURE",
};
export const scheduleInterviewConstants = {
  SCHEDULE_INTERVIEW_REQUEST: "SCHEDULE_INTERVIEW_REQUEST",
  SCHEDULE_INTERVIEW_SUCCESS: "SCHEDULE_INTERVIEW_SUCCESS",
  SCHEDULE_INTERVIEW_FAILURE: "SCHEDULE_INTERVIEW_FAILURE",
};
export const interviewFeedbackConstants = {
  INTERVIEW_FEEDBACK_REQUEST: "INTERVIEW_FEEDBACK_REQUEST",
  INTERVIEW_FEEDBACK_SUCCESS: "INTERVIEW_FEEDBACK_SUCCESS",
  INTERVIEW_FEEDBACK_FAILURE: "INTERVIEW_FEEDBACK_FAILURE",
};
export const forgetPasswordLinkConstants = {
  FORGET_PASSWORD_LINK_REQUEST: "FORGET_PASSWORD_LINK_REQUEST",
  FORGET_PASSWORD_LINK_SUCCESS: "FORGET_PASSWORD_LINK_SUCCESS",
  FORGET_PASSWORD_LINK_FAILURE: "FORGET_PASSWORD_LINK_FAILURE",
};
export const updatePasswordConstants = {
  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
};
export const enquiryConstants = {
  ENQUIRY_REQUEST: "ENQUIRY_REQUEST",
  ENQUIRY_SUCCESS: "ENQUIRY_SUCCESS",
  ENQUIRY_FAILURE: "ENQUIRY_FAILURE",
};
export const getEnquiryConstants = {
  GET_ENQUIRY_REQUEST: "GET_ENQUIRY_REQUEST",
  GET_ENQUIRY_SUCCESS: "GET_ENQUIRY_SUCCESS",
  GET_ENQUIRY_FAILURE: "GET_ENQUIRY_FAILURE",
};
export const updateEnquiryConstants = {
  UPDATE_ENQUIRY_REQUEST: "UPDATE_ENQUIRY_REQUEST",
  UPDATE_ENQUIRY_SUCCESS: "UPDATE_ENQUIRY_SUCCESS",
  UPDATE_ENQUIRY_FAILURE: "UPDATE_ENQUIRY_FAILURE",
};
export const updateInterviewDetailsConstants = {
  UPDATE_INTERVIEW_DETAILS_REQUEST: "UPDATE_INTERVIEW_DETAILS_REQUEST",
  UPDATE_INTERVIEW_DETAILS_SUCCESS: "UPDATE_INTERVIEW_DETAILS_SUCCESS",
  UPDATE_INTERVIEW_DETAILS_FAILURE: "UPDATE_INTERVIEW_DETAILS_FAILURE",
};
