export const commonConstants = {
  UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_REQUEST_SUCCESS: "UPLOAD_IMAGE_REQUEST_SUCCESS",
  UPLOAD_IMAGE_REQUEST_FAILURE: "UPLOAD_IMAGE_REQUEST_FAILURE",
  UPLOAD_IMAGE_FILE_REQUEST: "UPLOAD_IMAGE_FILE_REQUEST",
  UPLOAD_IMAGE_FILE_REQUEST_SUCCESS: "UPLOAD_IMAGE_FILE_REQUEST_SUCCESS",
  UPLOAD_IMAGE_FILE_REQUEST_FAILURE: "UPLOAD_IMAGE_FILE_REQUEST_FAILURE",
};

export const logoutConstants = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
};
export const applyJobConstants = {
  APPLY_JOB_REQUEST: "APPLY_JOB_REQUEST",
  APPLY_JOB_SUCCESS: "APPLY_JOB_SUCCESS",
  APPLY_JOB_FAILURE: "APPLY_JOB_FAILURE",
};
export const signupUserConstants = {
  SIGNUP_USER_REQUEST: "SIGNUP_USER_REQUEST",
  SIGNUP_USER_SUCCESS: "SIGNUP_USER_SUCCESS",
  SIGNUP_USER_FAILURE: "SIGNUP_USER_FAILURE",
};
export const getuserDetailsConstants = {
  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
};
export const updateUserDetailsConstants = {
  UPDATE_USER_DETAILS_REQUEST: "UPDATE_USER_DETAILS_REQUEST",
  UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
  UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE",
};
export const loginUserConstants = {
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
};
export const getAllUserConstants = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",
};
export const postFeedbackConstants = {
  POST_FEEDBACK_REQUEST: "POST_FEEDBACK_REQUEST",
  POST_FEEDBACK_SUCCESS: "POST_FEEDBACK_SUCCESS",
  POST_FEEDBACK_FAILURE: "POST_FEEDBACK_FAILURE",
};

export const getUserPermissionConstants = {
  GET_USER_PERMISSIONS_REQUEST: "GET_USER_PERMISSIONS_REQUEST",
  GET_USER_PERMISSIONS_SUCCESS: "GET_USER_PERMISSIONS_SUCCESS",
  GET_USER_PERMISSIONS_FAILURE: "GET_USER_PERMISSIONS_FAILURE",
};

export const interviewFeedbackConstants = {
  INTERVIEW_FEEDBACK_REQUEST: "INTERVIEW_FEEDBACK_REQUEST",
  INTERVIEW_FEEDBACK_SUCCESS: "INTERVIEW_FEEDBACK_SUCCESS",
  INTERVIEW_FEEDBACK_FAILURE: "INTERVIEW_FEEDBACK_FAILURE",
};
export const forgetPasswordLinkConstants = {
  FORGET_PASSWORD_LINK_REQUEST: "FORGET_PASSWORD_LINK_REQUEST",
  FORGET_PASSWORD_LINK_SUCCESS: "FORGET_PASSWORD_LINK_SUCCESS",
  FORGET_PASSWORD_LINK_FAILURE: "FORGET_PASSWORD_LINK_FAILURE",
};
export const updatePasswordConstants = {
  UPDATE_PASSWORD_REQUEST: "UPDATE_PASSWORD_REQUEST",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILURE: "UPDATE_PASSWORD_FAILURE",
};
export const enquiryConstants = {
  ENQUIRY_REQUEST: "ENQUIRY_REQUEST",
  ENQUIRY_SUCCESS: "ENQUIRY_SUCCESS",
  ENQUIRY_FAILURE: "ENQUIRY_FAILURE",
};
export const getEnquiryConstants = {
  GET_ENQUIRY_REQUEST: "GET_ENQUIRY_REQUEST",
  GET_ENQUIRY_SUCCESS: "GET_ENQUIRY_SUCCESS",
  GET_ENQUIRY_FAILURE: "GET_ENQUIRY_FAILURE",
};
export const updateEnquiryConstants = {
  UPDATE_ENQUIRY_REQUEST: "UPDATE_ENQUIRY_REQUEST",
  UPDATE_ENQUIRY_SUCCESS: "UPDATE_ENQUIRY_SUCCESS",
  UPDATE_ENQUIRY_FAILURE: "UPDATE_ENQUIRY_FAILURE",
};
export const sendMessageConstants = {
  SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",
};
export const getMessageConstants = {
  GET_MESSAGE_REQUEST: "GET_MESSAGE_REQUEST",
  GET_MESSAGE_SUCCESS: "GET_MESSAGE_SUCCESS",
  GET_MESSAGE_FAILURE: "GET_MESSAGE_FAILURE",
};
